-- ==============================================================================
-- SUPABASE SCHEMA: Secure Ephemeral File Sharing
-- ==============================================================================

-- 1. Create the files table
CREATE TABLE IF NOT EXISTS public.files (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    share_code VARCHAR(6) NOT NULL UNIQUE,
    file_path TEXT NOT NULL,
    original_filename TEXT NOT NULL,
    file_size BIGINT NOT NULL,
    mime_type TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('utc'::text, now()),
    expires_at TIMESTAMPTZ NOT NULL
);

-- 2. Performance indexes
CREATE INDEX IF NOT EXISTS idx_files_share_code ON public.files (share_code);
CREATE INDEX IF NOT EXISTS idx_files_expires_at ON public.files (expires_at);

-- 3. Enable Row Level Security (RLS)
ALTER TABLE public.files ENABLE ROW LEVEL SECURITY;

-- Block all direct anonymous / authenticated client operations by default.
-- All operations (upload, verify, delete) are strictly performed server-side
-- via the Next.js API routes using the Supabase Service Role Key.
-- This prevents any client from enumerating or viewing file hashes directly.
DROP POLICY IF EXISTS "Service role full access" ON public.files;
CREATE POLICY "Service role full access"
    ON public.files
    FOR ALL
    TO service_role
    USING (true)
    WITH CHECK (true);

-- 4. Storage Bucket Setup: 'secure-files'
-- Note: You can also create this bucket in the Supabase Dashboard > Storage > New Bucket:
-- Bucket Name: secure-files
-- Public: OFF (strictly private)
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES ('secure-files', 'secure-files', false, 52428800, null)
ON CONFLICT (id) DO UPDATE 
SET public = false, file_size_limit = 52428800;

-- 5. Storage Access Policies
-- Deny public anonymous downloads (must be signed URLs generated by service role)
DROP POLICY IF EXISTS "Private bucket service role access" ON storage.objects;
CREATE POLICY "Private bucket service role access"
    ON storage.objects
    FOR ALL
    TO service_role
    USING (bucket_id = 'secure-files')
    WITH CHECK (bucket_id = 'secure-files');

-- 6. Optional Database-level automated cleanup function
-- If using pg_cron (Supabase Pro/Self-hosted), this cleans expired database records.
-- (The Next.js `/api/cron/cleanup` endpoint also handles purging both Storage files and DB records)
CREATE OR REPLACE FUNCTION public.delete_expired_file_records()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
    DELETE FROM public.files
    WHERE expires_at < timezone('utc'::text, now());
END;
$$;

-- Comment for pg_cron if extension is available:
-- SELECT cron.schedule('cleanup-expired-files', '*/5 * * * *', 'SELECT public.delete_expired_file_records()');
